# Generated by Django 2.2.8 on 2019-12-09 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackInPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Playlist')),
                ('sublist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublist_set', to='client.Playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Track')),
            ],
            options={
                'ordering': ['playlist', 'position'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(through='client.TrackInPlaylist', to='client.Track'),
        ),
        migrations.AddConstraint(
            model_name='trackinplaylist',
            constraint=models.UniqueConstraint(fields=('playlist', 'position'), name='unique_position_in_playlist'),
        ),
    ]
