# Generated by Django 2.2.11 on 2020-04-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20191223_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackinplaylist',
            options={},
        ),
        migrations.RemoveField(
            model_name='trackinplaylist',
            name='sublist',
        ),
        migrations.AddField(
            model_name='playlist',
            name='has_local_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='sublists',
            field=models.ManyToManyField(related_name='parent_list_set', to='client.Playlist'),
        ),
    ]
